### ISSUE TITLE
Gradients ColorDistance

### ISSUE THREAD

**Issue by fasteddys** [R0tenur/color#1]
Hello I stumbled upon this great lib. by accident, I was reading your help page and would like some guidance.

Based on the number of steps/gradients/groups(some input Variable `NumOfColors`), I `need to create uniform color distribution of colors` in both `HSL `and `HexString `for Css/HTML output from C#.

For e.g. if they there are 20 groups of users to display (which are the steps/gradients), using your lib. how can I get 20 distinct uniform colors back?

___________________
to derive an output like so.. so I can embed it into the CSS file

```
.group.students.science       { background: #F11; background: hsl( 23, 80%, 60%); }
.group.students.travel          { background: #F21212; background: hsl( 33, 100%, 55%); }
...
```

**Comment by R0tenur** [comment]
Hello! Fun and a bit random that you have found this lib.
Unfortunately there are no support for any of the things you wish for.

But I would like clarification or certain things. What you want is:
 - n number of colors that  visually works well together
- HSL support

HSL is pretty simple it's more or less dividing each number i rgb by 255.
